name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build && tests
      run: cargo build --release && ./target/release/rusty tests.lisp && ./target/release/rusty new-features.lisp && ./target/release/rusty hello.lisp
    - name: Run test
      run: cargo run ./tests.lisp or cargo run ./your_program_name.lisp
    - name: Run rusty
      run: cargo run
